version: '3'
services:
    app:
        build: .
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=production
            - LK_API_KEY=${LK_API_KEY}
            - LK_API_SECRET=${LK_API_SECRET}
